# docker-compose
version: "3.6"

services:
  nginx_cms:
    image: "${IMAGE_NGINX}"
    volumes:
      - ./app/:/var/www
      - ./sites:/var/www/sites
      - ./logs:/var/log/nginx
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "${NGINX_SERVER_PORT:-8080}:80"
    depends_on:
      - app_cms

  app_cms:
    build: ./docker/php
    environment:
      APP_ENV: "${APP_ENV}"
    volumes:
      - ./app:/var/www
      - ./sites:/var/www/sites
